language: cpp

matrix:
  include:
    - os: osx

install:
  - brew update
  - brew install qt5
  - brew link --force qt5

script:
  - qmake PokeFinder.pro
  - make

before_deploy:
  - /usr/local/Cellar/qt/5.12.0/bin/macdeployqt PokeFinder.app -dmg -verbose=2
  - zip -r PokeFinder-macOS.zip PokeFinder.dmg

deploy:
  provider: releases
  api_key:
    secure: HEeoNmgC6cDkb87dQXGr4KqEVRCj4dPgK7HALMuUT1p9IXBbB1sC1hhKjtKNAJhc9yEH6LqSLGNtXSOfoxRsZnmd+JovJLEaFlC/66GqEzdtPoz22i9ilEbvpv1dmsvsg/4By2ZJvQtf5vDlZrXEEhCUCP4ntk3qmCUpwvzwiiR38kPllSqXNYWrE9Om+cZIib8QxaqjPbbUJaDsN4aXhnJ9KWhTQ0lNgn6/JhdESkPmbSOHbr7PcHGcXQIaaHFEGwjW1/DL9iymXAPbwm61gQ5NJs/U//0LqJiLhPwD3hNyuC2ns6bfg/PETpuqjIFxoDnIaVEfkTSn4Oo0ltCMDuKV+1oQl0IRx6RuYajjPAa0L1VMlWwGTeO/kn9dBWKAnEweJbAAchalcpypSzpmQPTKudRu3rx3Z2rSo402zRslLsy9gXWlOg5ZIHX1Ijj2hQ1flHQB74L4dnalmfjnRJQVWGhFZiCdQ3+WaD26n8dTZQ+Wf9WKZnZJSVJH1pQuj9jgUAjPZBwIIuEMCMGf+d8NE7QXbWuKcvuY7DKfHrhdBF0Y5U5QZBMqit7Gf45laO4P1WWikKemYV/SOIbHXSmx/TPVEeWhxBdq9+V+jTrp1/o/B/zpsAyNmhI6c6nk+QZN9U+Q0BNGi4FiZgvZcqPPkIkN9CeZHBJggLjb0GQ=
  file: "PokeFinder-macOS.zip"
  skip_cleanup: true
  prerelease: false
  on:
    repo: Admiral-Fish/PokeFinder
    tags: true
